### ISSUE TITLE
Nice Job!!!May I ask when it can be open sourced?

### ISSUE THREAD

**Issue by PigPigchick** [FaceG2E/FaceG2E#1]
Nice Job!!!May I ask when it can be open sourced?

**Comment by He-Chao** [comment]
The same question

**Comment by FaceG2E** [comment]
Thanks for your interest in our work. We will be opening the source code and model weights in several weeks. Please stay tuned.

**Comment by JiejiangWu** [comment]
Just a reminder, our code is now publicly available. See: [link](https://github.com/JiejiangWu/FaceG2E/)
